export { default as Seo } from './seo/seo' 
export { default as Navbar } from './navbar/navbar' 
export { default as Content } from './content/content' 
export { default as Footer } from './footer/footer' 
export { default as Hero } from './hero/hero'